title: 胡歌
author: 胡文耀
email: tmhuwenyao@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  "Hope is a good thing ,maybe the best thing of all.And no good things ever die!"        —— the Shawshank Redemption
github_username:  onpense
permalink: /:year/:month/:title/
timezone: Asia/Shenzhen

# Build settings
markdown: kramdown
highlighter: rouge

